config/routes.rb
Terora::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


	root :to => 'questions#index'

  resources :tags
	resources :updates

  get "tags/show"
  resources :questions do
		resources :answers do
		  member do
			  get :upvote
			  get :downvote
				get :accept_toggle
			end
		end
		member do
			get :upvote
			get :downvote
		end
	end

  get 'get_started/welcome'
	get 'pages/home'
	get 'pages/tags'
	get "about/home"

  devise_for :users, :controllers => { :registrations => 'registrations' },
		:path => '', :path_names => {:sign_in => 'login'}

	# User Profile
	get 'users/show'
	get 'user/:id' => 'users#show', as: :user


	# Help
	get "help" => 'help#home', as: :help
	get 'help/asking' => 'help#asking'
	get 'help/answering' => 'help#answering'
	get 'help/reputation' => 'help#reputation'
	get 'help/account' => 'help#account'

	# About
	get "about" => 'about#home'

	# Error Pages
	get "errors/error_404"
	get "errors/error_500"

	unless Rails.application.config.consider_all_requests_local
		get '*not_found', to: 'errors#error_404'
	end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

	# 1 = Registered
	# 2 = Banned
	# 3 = Moderator
	# 4 = Administrator

  def initialize(user)

		user ||= User.new # guest user (not logged in)

		if user.role_id == 4
			can :manage, :all # user can perform any action on any object
		else
			can :read, :all # user can read any object
			can :upvote, :all
			can :downvote, :all
			can :accept_toggle, Answer
			can :create, Question # can create Question

			# Can Update Question if owner
			can :update, Question do |question|
				question.try(:user) == user || user.role_id == 3
			end

			# Can destroy Question if owner
			can :destroy, Question do |question|
				question.try(:user) == user || user.role_id == 3
			end
		end



    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ActiveRecord::Base

	acts_as_votable

	belongs_to :user
	belongs_to :question

	validates :body, :presence => true
	validates :question_id, :presence => true
	validates :user_id, :presence => true

	def owner?(user)
		if self.user_id == user.id
		  return true
		 else
		 	return false
    end
	end
end

app/models/question.rb
class Question < ActiveRecord::Base
	is_impressionable
	acts_as_votable

	extend FriendlyId
	friendly_id :title, :use => [:slugged, :finders]

	belongs_to :user
	has_many :answers, :dependent => :destroy

  has_many :taggings
  has_many :tags, through: :taggings

	validates :title, :presence => true, length: { minimum: 15 }
	validates :body, :presence => true, length: { minimum: 30 }
	validates :user_id, :presence => true

	def has_accepted_answer?
		self.answers.where(accepted: true).any?
	end

	def owner?(user)
		if self.user_id == user.id
		  return true
		 else
		 	return false
    end
	end

  def self.tagged_with(name)
    Tag.find_by_name!(name).questions
  end

  def tag_list
    tags.map(&:name)
  end

  def tag_with(tags)
  	old_tags = self.tags.pluck(:name).unshift("")
  	unless old_tags == tags # if tags were not updated no action will be done.
	  	self.tags.delete_all
	  		# code here (in the future)
	  	tags.map do |n|
	    	tag = Tag.where(name: n.strip).first
	    	if tag.present?
	    		tagging = Tagging.find_or_create_by_tag_id_and_question_id(tag.id, self.id)
	    	  #Tagging.create(tag_id: tag.id, question_id: self.id)
	    	end
	 	  end
	 	end
  end

  def tag_list=(names)
  	self.tags = names.split(",").map do |n|
    	Tag.where(name: n.strip).first!
 	  end
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :questions, through: :taggings

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :question

end

app/models/update.rb
class Update < ActiveRecord::Base

	extend FriendlyId
	friendly_id :title, :use => [:slugged, :finders]

	validates :title, :presence => true
	validates :body, :presence => true
	# validates :cover, :presence => true

	# Cover
	has_attached_file :cover, styles: { cover: "870x200#" },
										:default_url => 'defulatpath.com',
										:path => ":rails_root/public/system/:attachment/:id/:style/:filename",
										:url => "/system/:attachment/:id/:style/:filename"

	validates_attachment :cover, content_type: { content_type: ['image/jpeg',
																															 'image/jpg',
																															 'image/png'] },
											 size: { less_than: 3.megabytes }


end

app/models/user.rb
class User < ActiveRecord::Base

  has_merit
	acts_as_voter

	extend FriendlyId
	friendly_id :user_name, :use => [:slugged, :finders]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	validates :first_name, :presence => true
	validates :user_name, :presence => true, :uniqueness => true
	validates :email, :presence => true, :uniqueness => true


	# User Avatar
	has_attached_file :avatar, styles: { mini: "32x32#", profile: "180x180#"},
										:default_url => 'https://s3.amazonaws.com/leagueio/design/user-profile/missing-image.png',
										:path => ":rails_root/public/system/:attachment/:id/:style/:filename",
										:url => "/system/:attachment/:id/:style/:filename"

	validates_attachment :avatar, content_type: { content_type: ['image/jpeg',
																															 'image/jpg',
																															 'image/png'] },
											 size: { less_than: 3.megabytes }


	# Relationships
	has_many :questions
	has_many :answers
	belongs_to :role


	before_create :set_default_role


	private

	def set_default_role
		self.role ||= Role.find_by_name('registered')
	end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
end

app/controllers/help_controller.rb
class HelpController < ApplicationController

	def home
	end

	def asking
	end

	def answering
	end

	def reputation
	end

	def account
	end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/get_started_helper.rb
module GetStartedHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/help/account.html.erb
<b>Coming soon...</b>

app/views/help/answering.html.erb
<ul class="breadcrumb">
  <li><%= link_to "Help", help_path %></li>
  <li class="active">Answering</li>
</ul>

<div class="row-fluid">

  <div class="span3">
    <ul class="nav nav-list league-docs-sidenav">
      <li><a href="#accepted"><i class="fui-arrow-right pull-right"></i> My Answer got accepted</a></li>
      <li><a href="#goodanswer"><i class="fui-arrow-right pull-right"></i> How do I write a good answer?</a></li>
      <li><a href="#deleted"><i class="fui-arrow-right pull-right"></i> My Answer got deleted</a></li>
    </ul>
  </div>

  <div class="span9">
    <div class="help_answering_hero">
      <h2>How to answer Questions</h2>
    </div>

    <!-- Content Starts Here-->

    <section id="accepted">

      <div class="help_topic_header">
        <h1><span class="fui-tag"></span> What does it mean when an answer is "accepted"?</h1>
      </div>

      <p>
        When a user receives a good answer to his or her question, that user has
        the option to <b>"accept"</b> an answer. Acceptance is indicated by a
        colored checkmark next to the answer that has been accepted by the
        original author of the question.
      </p>

      <p>
        Accepting an answer is not meant to be a definitive and final statement
        indicating that the question has now been answered perfectly. It simply
        means that the author received an answer that worked for him or her
        personally, but not every user comes back to accept an answer, and of
        those who do, they may not change the accepted answer if a newer,
        better answer comes along later.
      </p>

      <p>Often, accepting an answer corresponds to reputation gains.</p>

      <p>If you accept:</p>

      <ol>
        <li>
          <b>someone else's answer:</b> You gain +2 League Points and the author
          of the accepted answer earns +15 League Points.
        </li>
        <li>
          <b>your own answer:</b> No reputation is awarded, and the answer does
          not float to the top of the list.
        </li>
      </ol>

    </section>

    <br>

    <section id="goodanswer">

      <div class="help_topic_header">
        <h1><span class="fui-tag"></span>  How do I write a good answer?</h1>
      </div>

      <p>
        Thanks for taking the time to contribute an answer. It’s because of
        helpful peers like yourself that we’re able to learn together as a
        community. Here are a few tips on how to make your answer great:
      </p>

      <h5>Pay it forward</h5>

      <p>
        Saying “thanks” is appreciated, but it doesn’t answer the question.
        Instead, vote up the answers that helped you the most! If these answers
        were helpful to you, please consider saying thank you in a more
        constructive way – by contributing your own answers to questions your
        peers have asked here.
      </p>

      <h5>Have the same problem?</h5>

      <p>
        Still no answer to the question, and you have the same problem? Help us
        find a solution by researching the problem, then contribute the results
        of your research and anything additional you’ve tried as a partial answer.
        That way, even if we can’t figure it out, the next person has more to
        go on. You can also vote up the question.
      </p>

      <h5>Answer the question</h5>

      <p>
        Read the question carefully. What, specifically, is the question asking
        for? Make sure your answer provides that – or a viable alternative.
        The answer can be “don’t do that”, but it should also include
        “try this instead”. Any answer that gets the asker going in the right
        direction is helpful, but do try to mention any limitations,
        assumptions or simplifications in your answer. Brevity is acceptable,
        but fuller explanations are better.
      </p>

      <h5>Provide context for links</h5>

      <p>
        Links to external resources are encouraged, but please add context
        around the link so your fellow users will have some idea what it is and
        why it’s there. Always quote the most relevant part of an important link,
        in case the target site is unreachable or goes permanently offline.
      </p>

      <h5>Write to the best of your ability</h5>

      <p>
        We don't expect every answer to be perfect, but answers with correct
        spelling, punctuation, and grammar are easier to read. They also tend to
        get upvoted more frequently. Remember, you can always go back at any
        time and edit your answer to improve it.
      </p>

      <h5>Always be polite and have fun</h5>

      <p>
        It’s fine to disagree and express concern, but please be civil. There’s
        a real human being on the other end of that network connection,
        however misguided they may appear to be. We’re here to learn from our
        peers, not yell at each other.
      </p>

    </section>

    <br>

    <section id="deleted">

      <div class="help_topic_header">
        <h1><span class="fui-tag"></span>  Why and how are some answers deleted?</h1>
      </div>

      <p>
        Answers that <b>do not fundamentally answer the question</b> may be
        removed. This includes answers that are:
      </p>

      <ol>
        <li>commentary on the question or other answers</li>
        <li>asking another, different question</li>
        <li>“thanks!” or “me too!” responses</li>
        <li>exact duplicates of other answers</li>
        <li>barely more than a link to an external site</li>
        <li>not even a partial answer to the actual question</li>
      </ol>

      <p>
        If you wish to improve an existing answer, click the edit link beneath it.
        For more guidance, see <a href="#goodanswer">How to Answer</a>.</p>

      <p>Additionally, any answer that accumulates enough offensive or spam flags will be automatically deleted.

    </section>


  </div>

</div>

app/views/help/asking.html.erb
<ul class="breadcrumb">
  <li><%= link_to "Help", help_path %></li>
  <li class="active">Asking</li>
</ul>

<div class="row-fluid">

  <div class="span3">

    <ul class="nav nav-list league-docs-sidenav">
      <li><a href="#topics"><i class="fui-arrow-right pull-right"></i> What Topics can i ask</a></li>
      <li><a href="#avoid"><i class="fui-arrow-right pull-right"></i> What to avoid asking</a></li>
      <li><a href="#deleted"><i class="fui-arrow-right pull-right"></i> How are Questions deleted</a></li>
      <li><a href="#tags"><i class="fui-arrow-right pull-right"></i> What are Tags</a></li>
      <li><a href="#answered"><i class="fui-arrow-right pull-right"></i> My Question got answered</a></li>
      <li><a href="#goodquestion"><i class="fui-arrow-right pull-right"></i> How to ask a good Question</a></li>
    </ul>

  </div>

  <div class="span9">

    <div class="help_asking_hero">
      <h2>Asking is OP</h2>
    </div>


    <!-- Content Starts Here-->

    <section id="topics">
      <div class="help_topic_header">
        <h1><span class="fui-tag"></span> What Topics can i ask around here</h1>
      </div>

      <p>
        League I/O is for professional and enthusiast League of Legends Players,
        people who love the Game and want to contribute to the Community. If your
        Questions generally cover:
      </p>

      <ol>
        <li>a League of Legends related Problem</li>
        <li>practical, answerable problems</li>
        <li>a minimum understanding of the Problem</li>
      </ol>

      <br>

      <p>… then you’re in the right place to ask your question!</p>

      <p>
        Please look around to see if your question has been asked before.
        Questions which are too broad, unclear, or primarily opinion-based may
        be put on hold by the community until they are improved.
      </p>


    </section>  <!--Topic Section End-->

    <br>

    <section id="avoid">
      <div class="help_topic_header">
        <h1><span class="fui-tag"></span> What types of questions should I avoid asking?</h1>
      </div>

      <p>First, make sure that your question is <b>on-topic for this site</b>.</p>

      <p>
        You should only ask practical, answerable questions based on actual
        problems that you face. Chatty, open-ended questions diminish the
        usefulness of our site and push other questions off the front page.
      </p>


      <p>
        Your questions should be reasonably scoped. If you can imagine an entire
        book that answers your question, you’re asking too much.
      </p>

      <p>
        If your motivation for asking the question is “I would like to
        participate in a discussion about ______”, then you should not be asking
        here. However, if your motivation is “I would like others to
        explain ______ to me”, then you are probably OK.
      </p>

      <p>
        <b>
          To prevent your question from being flagged and possibly removed,
          <i>avoid</i> asking subjective questions where …
        </b>
      </p>

      <ol>
        <li>every answer is equally valid: “What’s your favorite ______?”</li>
        <li>your answer is provided along with the question, and you expect more answers: “I use ______ for ______, what do you use?”</li>
        <li>there is no actual problem to be solved: “I’m curious if other people feel like I do.”</li>
        <li>you are asking an open-ended, hypothetical question: “What if ______ happened?”</li>
        <li>your question is just a rant in disguise: “______ sucks, am I right?”</li>
      </ol>

      <br>

      <p><b>Some subjective questions are allowed, but “subjective” does not mean “anything goes”. All subjective questions are expected to be <i>constructive</i></b>. What does that mean? Constructive subjective questions:</p>

      <ol>
        <li>inspire answers that explain “why” and “how”</li>
        <li>tend to have long, not short, answers</li>
        <li>have a constructive, fair, and impartial tone</li>
        <li>invite sharing experiences over opinions</li>
        <li>insist that opinion be backed up with facts and references</li>
        <li>are more than just mindless social fun</li>
      </ol>

    </section> <!--Avoid section End-->

    <br>

    <section id="deleted">
      <div class="help_topic_header">
        <h1><span class="fui-tag"></span> Why and how are some questions deleted?</h1>
      </div>

      <p>
        Questions that are <b>extremely off topic</b>, or of very low quality,
        may be removed at the discretion of the community and moderators.

        Over time, closed questions that are not useful as signpoints to other
        questions may also be removed, as well as questions which have no
        significant activity over a very long period after being asked. If you
        want to improve a question to keep it from being deleted, click the
        edit button beneath it.
      </p>

      <p>
        Additionally, any answer that accumulates enough offensive or spam
        flags will be automatically deleted.
      </p>

      <p>
        <b>
          Users can delete their own questions if the question has zero answers
        </b>
      </p>


      <p>Simply click the delete link underneath the question.</p>

      <p>
        Questions can also be deleted by the community. Moderators can delete
        any question, and users with sufficient reputation can cast delete votes
        on closed questions. It takes 3 votes, minimum, to delete a closed
        question. However, the number of delete votes required scales to the
        number of votes on the question and all its answers.
      </p>

    </section>  <!-- Deleted Section End-->

    <br>

    <section id="tags">
      <div class="help_topic_header">
        <h1><span class="fui-tag"></span> What are tags, and how should I use them?</h1>
      </div>

      <p>
        A tag is a word or phrase that describes the topic of the question.
        Tags are a means of connecting experts with questions they will be able
        to answer by sorting questions into specific, well-defined categories.
      </p>

      <p>
        Tags can also be used to help you identify questions that are
        interesting or relevant to you.
      </p>

      <p>
        Clicking on a tag below a question brings you to a page that shows all
        questions within that tag. You also see a description of what the tag is
        and how it should be applied on League I/O (since sometimes the tag name
        is a common word that has a broad meaning in the real world but a very
        particular, narrow meaning on this site.)
      </p>

      <p>
        Each question <b>may only contain 5 tags at a maximum</b>, so choose the ones
        that best describe your question.
      </p>

      <h3>Re-tagging</h3>

      <p>
        As part of the editing process, users may
        suggest edits or directly edit the tags of a question if they feel a
        certain tag was used inappropriately or that the question is missing a tag.
      </p>

      <p>You should re-tag questions when:</p>

      <ol>
        <li>
          You are adding valuable information to the question by doing so
        </li>
        <li>
          You are replacing obscure or difficult to understand tags with
          well-known and popular tags that are appropriate for the question.
        </li>
      </ol>

      <br>

      <h4>Should I use tags in titles?</h4>

      <p>
        You should not <em>force</em> a tag into your title. Because the tags
        appear below the question and tags are indexed by search engines along
        with the content of your question, you can trust that other people will
        be able to find your question based on tags they follow or search for.
        Additionally, tags appear on the question page, so other people will
        take them into account when answering your question.
      </p>

      <p>
        <em><strong>Avoid</strong></em> inserting tags into titles in any of
        the following formats:
      </p>

      <ol>
        <li>[tag]: [question title]</li>
        <li>[question title] -- [tag] [tag] [tag]</li>
        <li>[question title] in [tag]</li>
        <li>[tag] [tag] [question title] [tag] [tag] [tag]</li>
        <li>[tag] [tag] [tag] [tag] [tag] [tag] [tag] [tag]</li>
      </ol>

      <br>

      <p>
        <b>
          The only time you should use tags in your title is when they are
          organic to the conversational tone of the title.
        </b>
      </p>

    </section>   <!-- Tags Section End-->

    <br>

    <section id="answered">
      <div class="help_topic_header">
        <h1><span class="fui-tag"></span> What should I do when someone answers my question?</h1>
      </div>

      <p>
        The first thing you should do when someone answers your question is
        vote on it, like any other user does. Vote up answers that are helpful
        and well-researched, and vote down answers that are not. Other users
        will also vote on answers to your question.
      </p>

      <p>
        As the author of the question, you have an additional option:
        accepting an answer that you believe is the best solution to your problem.
      </p>

      <p><b>To accept an answer:</b></p>

      <ol>
        <li>Choose one answer that you believe is the best solution to your problem.</li>
        <li>To mark an answer as accepted, click on the check mark beside the answer to toggle it from greyed out to filled in.</li>
        <li>You may change which answer is accepted, or simply un-accept the answer, at any time.</li>
      </ol>

      <br>

      <p>
        Accepting an answer is not mandatory; do not feel compelled to accept
        the first answer you receive. Wait until you receive an answer that
        answers your question well.
      </p>

    </section> <!-- Answered Section End-->

    <br>

    <section id="goodquestion">
      <div class="help_topic_header">
        <h1><span class="fui-tag"></span> How do I ask a good question?</h1>
      </div>

        <p>
          We’d love to help you. To <b>improve your chances</b> of getting an
          answer, here are some tips:
        </p>

        <h5>Search, and research</h5>

        <p>
          Have you <b>thoroughly searched for an answer</b> <i>before</i>
          asking your question? Sharing your research helps everyone.
          Tell us what you found and why it didn’t meet your needs.
          This demonstrates that you’ve taken the time to try to help yourself,
          it saves us from reiterating obvious answers, and above all, it helps
          you get a more specific and relevant answer!
        </p>

        <br>

        <h5>Be on-topic</h5>

        <p>
          Our community is defined by a specific set of topics that you can
          view in the help center; please stick to those topics and avoid asking
          for opinions or open-ended discussion.
        </p>

        <br>

        <h5>Be specific</h5>

        <p>
          If you ask a vague question, you’ll get a vague answer. But if you
          give us details and context, we can provide a useful answer.
        </p>

        <br>

        <h5>Make it relevant to others</h5>

        <p>
          We like to help as many people at a time as we can. Make it clear how
          your question is relevant to more people than just you, and more of us
          will be interested in your question and willing to look into it.
        </p>

        <br>

        <h5>Keep an open mind</h5>

        <p>
          The answer to your question may not always be the one you wanted,
          but that doesn’t mean it is wrong. A conclusive answer isn’t always
          possible. When in doubt, ask people to cite their sources, or to
          explain how/where they learned something. Even if we don’t agree with
          you, or tell you exactly what you wanted to hear,
          remember: <b>we’re just trying to help</b>.
        </p>

    </section>   <!-- Good Question Section End-->


  </div><!-- Span 9 End -->

</div>

app/views/help/home.html.erb
<div class="help-hero-unit">

  <div class="pull-left">
    <h1>New to League I/O ?</h1>
  </div>

  <div class="pull-right desc">
    <b>Here's how it works:</b>
    <ol>
      <li>Anybody can ask a question</li>
      <li>Anybody can answer</li>
      <li>The best answers are voted up</li>
    </ol>
  </div>

  <div class="clearfix"></div>
</div>

<div class="_hd_foma">
  <h3>Find out more about...</h3>
</div>

<div class="h_w">

  <div class="_hd">
    <%= link_to help_asking_path do %>
      <%= image_tag("https://s3.amazonaws.com/leagueio/design/help/main/asking-main.png") %>
      <b class="hd_b"> Asking  </b>
    <% end %>
  </div>

  <div class="_hd">
    <%= link_to help_answering_path do %>
      <%= image_tag("https://s3.amazonaws.com/leagueio/design/help/main/answering-main.png") %>
      <b class="hd_b"> Answering </b>
    <% end %>
  </div>

  <div class="_hd">
    <%= link_to help_reputation_path do %>
      <%= image_tag("https://s3.amazonaws.com/leagueio/design/help/main/league-points-main.png") %>
      <b class="hd_b"> League Points </b>
    <% end %>
  </div>

  <div class="_hd">
    <%= link_to help_account_path do %>
      <%= image_tag("https://s3.amazonaws.com/leagueio/design/help/main/account-main.png") %>
      <b class="hd_b"> My Account </b>
    <% end %>
  </div>

</div>