config/routes.rb
Terora::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


	root :to => 'questions#index'

  resources :tags
	resources :updates

  get "tags/show"
  resources :questions do
		resources :answers do
		  member do
			  get :upvote
			  get :downvote
				get :accept_toggle
			end
		end
		member do
			get :upvote
			get :downvote
		end
	end

  get 'get_started/welcome'
	get 'pages/home'
	get 'pages/tags'
	get "about/home"

  devise_for :users, :controllers => { :registrations => 'registrations' },
		:path => '', :path_names => {:sign_in => 'login'}

	# User Profile
	get 'users/show'
	get 'user/:id' => 'users#show', as: :user


	# Help
	get "help" => 'help#home', as: :help
	get 'help/asking' => 'help#asking'
	get 'help/answering' => 'help#answering'
	get 'help/reputation' => 'help#reputation'
	get 'help/account' => 'help#account'

	# About
	get "about" => 'about#home'

	# Error Pages
	get "errors/error_404"
	get "errors/error_500"

	unless Rails.application.config.consider_all_requests_local
		get '*not_found', to: 'errors#error_404'
	end

end

app/models/question.rb
class Question < ActiveRecord::Base
	is_impressionable
	acts_as_votable

	extend FriendlyId
	friendly_id :title, :use => [:slugged, :finders]

	belongs_to :user
	has_many :answers, :dependent => :destroy

  has_many :taggings
  has_many :tags, through: :taggings

	validates :title, :presence => true, length: { minimum: 15 }
	validates :body, :presence => true, length: { minimum: 30 }
	validates :user_id, :presence => true

	def has_accepted_answer?
		self.answers.where(accepted: true).any?
	end

	def owner?(user)
		if self.user_id == user.id
		  return true
		 else
		 	return false
    end
	end

  def self.tagged_with(name)
    Tag.find_by_name!(name).questions
  end

  def tag_list
    tags.map(&:name)
  end

  def tag_with(tags)
  	old_tags = self.tags.pluck(:name).unshift("")
  	unless old_tags == tags # if tags were not updated no action will be done.
	  	self.tags.delete_all
	  		# code here (in the future)
	  	tags.map do |n|
	    	tag = Tag.where(name: n.strip).first
	    	if tag.present?
	    		tagging = Tagging.find_or_create_by_tag_id_and_question_id(tag.id, self.id)
	    	  #Tagging.create(tag_id: tag.id, question_id: self.id)
	    	end
	 	  end
	 	end
  end

  def tag_list=(names)
  	self.tags = names.split(",").map do |n|
    	Tag.where(name: n.strip).first!
 	  end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	# Views Counter
	impressionist :actions => [:show]

  before_action :set_question, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, :except => [:index, :show]

	# Cancan
	load_and_authorize_resource except: [:create]

	# GET /questions
  # GET /questions.json
  def index
		# Tags
		if params[:tag]
			@questions = Question.tagged_with(params[:tag])
		else
			@questions = Question.order("created_at desc")
		end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = current_user.questions.new
  end

  # GET /questions/1/edit
	def edit
		if current_user.role_id == 4
			@question = Question.find(params[:id])
		else
			@question = current_user.questions.find(params[:id])
		end
	end

  # POST /questions
  # POST /questions.json
  def create
    @question = current_user.questions.new(question_params)

    respond_to do |format|
      if @question.save
      	# add tags
        @question.tag_with(params[:question][:tag_list])
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
      	# update tags
      	@question.tag_with(params[:question][:tag_list])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
	end

	def upvote
		@question = Question.find(params[:id])
    if @question.owner?(current_user)
      message = "You can't vote for your own question."
    else
  		if current_user.liked? @question
        message = "You have voted for this question."
      else
        if current_user.disliked? @question # will remove downvote, not upvote
          @question.find_votes(voter_id: current_user.id).first.destroy  # remove downvote.
          @question.user.add_points(2) # add 2 points previously removed on downvoting
          increment_votes_count
          message = "Downvote removed!"
        else
          current_user.up_votes @question
  			  @question.user.add_points(5)
          increment_votes_count
          message = "Vote added!" # test time !:)
  		  end
      end
    end
		redirect_to :back, notice: message
	end

	def downvote
		@question = Question.find(params[:id])
    if @question.owner?(current_user)
      message = "You can't vote for your own question"
    else
      if current_user.disliked? @question
        message = "You can downvote only once."
      else
    		if current_user.liked? @question # it will remove the upvote, not downvoting
    			@question.find_votes(voter_id: current_user.id).first.destroy #remove upvote
          @question.user.substract_points(5)
          decrement_votes_count # adds back +1 vote
          message = "Vote removed"
    		else
    			current_user.down_votes @question
    			@question.user.substract_points(2)
          decrement_votes_count
          message = "You downvoted this Question."
    		end
      end
		end
    redirect_to :back, notice: message
	end 

  def decrement_votes_count
    @question.decrement!(:votes_count)
    @question.save
  end

  def increment_votes_count
    @question.increment!(:votes_count)
    @question.save
  end
  # Selfvote for current_user so he can't upvote himself
  # selfvote method is useless oh, you can check this directly in the upvote/downvote method
  # That was my initial idea, but the 2 methods was getting so big that i thought i make it that way
  # bad practice ?
  # look, that should do it for the question owner. Cool, can i pass the message ?


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :body, :answer, :tag_list, :slug)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<div class="row-fluid">

  <div class="span9">
    <%= simple_form_for(@question) do |f| %>
      <%= f.error_notification %>

      <%= f.input :title %>
      <%= f.input :body, :as => :ckeditor %>
      <%#= f.input :tag_list, input_html: { class: "tagsinput "} %>
      <%= f.collection_select :tag_list, Tag.order(:name), :name, :name, {}, {multiple: true} %>

      <div class="form-actions">
        <%= f.button :submit %>
      </div>
    <% end %>
  </div>

  <div class="span3">
    <div class="nw_quest_how">
      How to Ask
      Is your question about Ubuntu?

      We prefer questions that can be answered, not just discussed.

      Provide details. Share your research.

      If your question is about this website, ask it on meta instead.

      visit the help center »
      asking help »
    </div>
  </div>

</div>

app/views/questions/_question.html.erb

<div class="question-summary narrow">
  <%= link_to question do %>
    <div class="cp">

      <!--Votes-->
      <div class="votes">
        <div class="mini-counts">
          <%= question.votes_count %>
        </div>
        <div>
          <% if question.votes_count == 1 %>
            Vote
          <% else %>
            Votes
          <% end %>
        </div>
      </div>
      <!--Votes End-->

      <!--Answers-->
      <% if question.answers.count == 0 %>
        <div class="status unanswered ">
          <div class="mini-counts"><%= question.answers.count %></div>
          <div>answers</div>
        </div>
      <% else %>
        <div class="status">
          <div class="mini-counts"><%= question.answers.count %></div>
          <div>
            <% if question.answers.count == 1 %>
              answer
            <% else %>
              answers
            <% end %>
          </div>
        </div>
      <% end %>
      <!--Answers End-->

      <!--Views-->
      <div class="views">
        <% if question.impressionist_count(:filter=>:session_hash) > 100 %>
          <div class="mini-counts hot"><%= question.impressionist_count(:filter=>:session_hash) %></div>
          <div class="hot">views</div>
        <% else %>
          <div class="mini-counts"><%= question.impressionist_count(:filter=>:session_hash) %></div>
          <div>
            <% if question.impressionist_count(:filter=>:session_hash) == 1 %>
              View
            <% else %>
              Views
            <% end %>
          </div>
        <% end %>
      </div>
      <!--Views End-->

    </div>
  <% end %>


  <div class="summary">
    <p>
      <b>
        <%= link_to question.title, question %>
      </b>
    </p>

    <div class="question-tags pull-left">
      <% question.tags.each do |tag| %>
        <span class="label label-default">
          <%= link_to tag.name, tag_path(tag.name) %>
        </span>
      <% end %>
    </div>

    <div class="started">

      <span class="relativetime">
        <%= time_ago_in_words(question.created_at) %> ago
      </span>

      <%= link_to question.user.user_name, question.user %>
      <span class="reputation-score" title="reputation score">
        <%= question.user.points %>
      </span>

    </div>
  </div>

</div>

<div class="clearfix"></div>

app/views/questions/edit.html.erb
<div class="row">

  <div class="span9">

    <h1>Editing question</h1>
    <%= simple_form_for(@question) do |f| %>
      <%= f.error_notification %>

      <%= f.input :title, input_html: { class: 'span5' }, label: false,
                  placeholder: "What's your Question? Be specific." %>

      <%#= f.input :body, input_html: { :class => "redactor" }, label: false %>

      <%= f.input :body, :as => :ckeditor, label: false %>



      <%= f.collection_select :tag_list, Tag.order(:name), :name, :name, {},
                              {multiple: true} %>

      <div class="form-actions">
        <%= f.submit "Post your Question", class: "btn btn-info" %>
      </div>
    <% end %>
  </div>

  <div class="span3">

    <div class="nw_quest_how">
      <p class="big"><b>How to Ask</b></p>
      <br>
      <p class="first" style="text-align: center">
        <b>Is your Question <br>about league of Legends?</b>
      </p>
      <br>
      <p style="text-align: center">
        We prefer questions that can be <i>answered</i>, not just discussed.
      </p>
      <br>
      <p style="text-align: center">Provide details.</p>
    </div>

    <br>

    <div class="nw_quest_links">
      <br>
      <p class="nw_quest_links_hpdesk" style="text-align: center">
        <b><%= link_to help_path do %>
            Visit the Help Desk <span class="fui-arrow-right"></span>
          <% end %>
        </b>
      </p>
      <p class="nw_quest_links_qhp" style="text-align: center">
        <b><%= link_to help_path  do %>
            Asking Help <span class="fui-arrow-right"></span>
          <% end %>
        </b>
      </p>
    </div>

  </div>

</div>

app/views/questions/index.html.erb
<% if user_signed_in? %>
  <div class="row-fluid">

    <div class="span9">
      <%= render @questions %>
    </div>

    <div class="span3">

      <div class="index_wlcm_beta">
        Welcome to the closed Beta <br>
        <%= current_user.first_name %>
        <br>
        <br>
        Feel free to roam around <br>
        and give us Feedback
      </div>

      <br><br><br><br><br>

      <div class="hero_logo">
        <%= link_to updates_path, :rel => "tooltip", "data-original-title" => "We've launched our new Blog" do  %>
        <div id="outline">
          <div id="inner-outline">
            <span class="fui-bubble"></span>
          </div>
        </div>
        <% end %>
      </div>


    </div>

  </div>
<% else %>

  <div class="hey_alert">
    <button type="button" class="close fui-cross" data-dismiss="alert"></button>
    <h3>Welcome to League I/O</h3>

    <div class="pull-left">
      <p>
        League I/O is for professional and <br>
        enthusiast League of Legends Players
      </p>
    </div>

    <div class="pull-right hey_plrght">
      <b>Here's how it works:</b>
      <ol>
        <li>Anybody can ask a question</li>
        <li>Anybody can answer</li>
        <li>The best answers are voted up</li>
      </ol>
    </div>

    <div class="clearfix"></div>

    <%= link_to "Tell me more", about_path, class: "btn btn-small btn-embossed" %>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-info btn-embossed" %>

  </div>

  <br>

  <div class="row-fluid">

    <div class="span9">
      <%= render @questions %>
    </div>

    <div class="span3">

      <div class="unrgstr_index_wlcm_beta">
        Welcome to the closed Beta <br>
        Summoner
        <br>
        <br>
        Feel free to roam around <br>
        and give us Feedback
      </div>

      <br><br><br><br><br>

      <div class="hero_logo">
        <%= link_to updates_path, :rel => "tooltip", "data-original-title" => "We've launched our new Blog" do  %>
          <div id="outline">
            <div id="inner-outline">
              <span class="fui-bubble"></span>
            </div>
          </div>
        <% end %>
      </div>


    </div>

  </div>


<% end %>

app/views/questions/new.html.erb
<div class="row">

  <div class="span9">
    <%= simple_form_for(@question) do |f| %>
      <%= f.error_notification %>

      <%= f.input :title, input_html: { class: 'span5' }, label: false,
                  placeholder: "What's your Question? Be specific." %>

      <%= f.input :body, :as => :ckeditor, label: false %>

      <%= f.collection_select :tag_list, Tag.order(:name), :name, :name, {},
                              {multiple: true} %>

      <div class="form-actions">
        <%= f.submit "Post your Question", class: "btn btn-info" %>
      </div>
    <% end %>
  </div>

  <div class="span3">

    <div class="nw_quest_how">
      <p class="big"><b>How to Ask</b></p>
      <br>
      <p class="first" style="text-align: center">
        <b>Is your Question <br>about league of Legends?</b>
      </p>
      <br>
      <p style="text-align: center">
        We prefer questions that can be <i>answered</i>, not just discussed.
      </p>
      <br>
      <p style="text-align: center">Provide details.</p>
    </div>

    <br>

    <div class="nw_quest_links">
      <br>
      <p class="nw_quest_links_hpdesk" style="text-align: center">
        <b><%= link_to help_path do %>
            Visit the Help Desk <span class="fui-arrow-right"></span>
            <% end %>
            </b>
      </p>
      <p class="nw_quest_links_qhp" style="text-align: center">
        <b><%= link_to help_asking_path :anchor => "goodquestion" do %>
            Asking Help <span class="fui-arrow-right"></span>
            <% end %>
            </b>
      </p>
    </div>

  </div>

</div>

app/views/questions/show.html.erb
<% set_meta_tags :title => "#{@question.title}",
                 :description => "#{@question.body}" %>

<%= display_meta_tags :og => {
        :title => "#{@question.title}",
        :description => "#{@question.body}",
        :image => "https://s3.amazonaws.com/leagueio/design/image-meta.png",
        :type  => "website",
        :url => "http://www.leagueio.com"
} %>

<div class="question_title">
  <h1>
    <%= link_to @question.title, @question %>
  </h1>
</div>



<div class="row-fluid">

  <div class="span1">

    <div style="text-align: center;">
        <div class="votebar">
        <ul>
          <li>
            <%= link_to "", upvote_question_path(@question),
                        class: "fui-triangle-up", title: "This Question shows Research effort. It is useful and clear" %>
          </li>
          <li style="color: #bcbcbc; font-weight: bold">
            <%= @question.votes_count %>
          </li>
          <li>
            <%= link_to "", downvote_question_path(@question),
                        class: "fui-triangle-down", title: "This question does not show any research effort; it is unclear or not useful" %>
          </li>
        </ul>
      </div>
    </div>

  </div> <!-- Span 1 End -->

  <div class="span8">

    <div class="qest_inner_boddy">
      <%= sanitize(raw(@question.body)) %>
    </div>



    <!-- Under Question Tags-->
    <div class="question-tags quest_shw">
      <% @question.tags.each do |tag| %>
        <span class="label label-default">
          <%= link_to tag.name, tag_path(tag.name) %>
        </span>
      <% end %>
    </div>

    <div class="quest_uc">
      <div class="pull-left">
        <% if can? :update, @question %>
          <small><%= link_to 'Edit', edit_question_path(@question) %> </small> |
        <% end %>
        <% if can? :destroy, @question %>
          <small><%= link_to 'Delete', @question, :data => { :confirm => "Are you sure you want to delete your Question?" }, method: :delete %></small> &nbsp;
        <% end %>

      </div>
      <!-- AddThis Button BEGIN -->
      <div class="addthis_toolbox addthis_default_style addthis_16x16_style">
        <a class="addthis_button_facebook"></a>
        <a class="addthis_button_twitter"></a>
        <a class="addthis_button_google_plusone_share"></a>
      </div>
      <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-51e7733c196e2f4b"></script>
      <!-- AddThis Button END -->

      <!-- Question Owner(User) -->
      <div class="pull-right owner">
        <td class="post-signature">


          <div class="user-info ">
            <div class="user-action-time">
              asked <%= time_ago_in_words(@question.created_at) %> ago
            </div>
            <div class="user-avtr32">
              <%= link_to (image_tag(@question.user.avatar(:mini))), @question.user %>
            </div>
            <div class="user-details">
              <%= link_to @question.user.user_name, @question.user %><br>
              <span class="reputation-score" title="reputation score" id="question_owner_reputation_score_<%= @question.id %>">
                <%= @question.user.points %>
              </span>
            </div>
          </div>

        </td>
      </div>
    </div>


  </div> <!-- Span 8 End-->

  <div class="span3">

    <div class="quest_wdgt">
      <b>
        <span class="fui-tag"></span>
        <%= @question.impressionist_count(:filter=>:session_hash) %>
        <% if @question.impressionist_count(:filter=>:session_hash) > 1 %>
          Views
        <% else %>
          View
        <% end %>
      </b>
    </div>

    <br>

    <div class="quest_mr_inf">
      Not the answer you're looking for?
      Browse other questions tagged
      <br>
      <div class="question-tags">
        <br>
        <% @question.tags.each do |tag| %>
        <span class="label label-default">
          <%= link_to tag.name, tag_path(tag.name)%>
        </span>
        <% end %>
      </div>
      <br>
      or  <%= link_to "ask your own question", new_question_path %>
    </div>

  </div> <!-- Span 3 End -->

</div>

<div class="row"><!-- Answers Area -->

  <div class="span9">
    <div class="quest_answrs">
      <% if @question.answers.present? %>
        <ul class="nav nav-tabs">
          <li class="active">
            <a><span class="answers_counter"><%= @question.answers.count %></span>
              &nbsp; &nbsp; Answers</a>
          </li>
        </ul>
      <% else %>
        <ul class="nav nav-tabs">
          <li class="active"><a>No Answers yet</a></li>
        </ul>
      <% end %>
    </div>
  </div>

</div>

<br>

<div class="">
  <%= render @question.answers.order(accepted: :desc, votes_count: :desc)%>
</div>

<% if user_signed_in? %>
  <div class="row">

  <div class="span8">
    <%= simple_form_for([@question, @question.answers.new]) do |f| %>
      <%= f.error_notification %>

      <%= f.input :body, :as => :ckeditor, label: false %>

      <div class="form-actions">
        <%= f.submit "Post your Answer", class: "btn btn-info" %>
      </div>
    <% end %>
  </div>

</div>
<% end %>