config/routes.rb
Terora::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


	root :to => 'questions#index'

  resources :tags
	resources :updates

  get "tags/show"
  resources :questions do
		resources :answers do
		  member do
			  get :upvote
			  get :downvote
				get :accept_toggle
			end
		end
		member do
			get :upvote
			get :downvote
		end
	end

  get 'get_started/welcome'
	get 'pages/home'
	get 'pages/tags'
	get "about/home"

  devise_for :users, :controllers => { :registrations => 'registrations' },
		:path => '', :path_names => {:sign_in => 'login'}

	# User Profile
	get 'users/show'
	get 'user/:id' => 'users#show', as: :user


	# Help
	get "help" => 'help#home', as: :help
	get 'help/asking' => 'help#asking'
	get 'help/answering' => 'help#answering'
	get 'help/reputation' => 'help#reputation'
	get 'help/account' => 'help#account'

	# About
	get "about" => 'about#home'

	# Error Pages
	get "errors/error_404"
	get "errors/error_500"

	unless Rails.application.config.consider_all_requests_local
		get '*not_found', to: 'errors#error_404'
	end

end

app/models/answer.rb
class Answer < ActiveRecord::Base

	acts_as_votable

	belongs_to :user
	belongs_to :question

	validates :body, :presence => true
	validates :question_id, :presence => true
	validates :user_id, :presence => true

	def owner?(user)
		if self.user_id == user.id
		  return true
		 else
		 	return false
    end
	end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	# Cancan
	load_and_authorize_resource except: [:create]

	before_action :set_answer, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!



	# GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
		@answer = current_user.answers.new  # User_id
  end

  # GET /answers/1/edit
  def edit
		if current_user.role_id == 4
			@question = Question.find(params[:question_id])
    	@answer = Answer.find(params[:id])  # User_id
		else
			@question = Question.find(params[:question_id])
			@answer = current_user.answers.find(params[:id])  # User_id
	  end
  end

  # POST /answers
  # POST /answers.json
  def create
		@question = Question.find(params[:question_id])
    @answer = current_user.answers.new(answer_params)  # User_id
		@answer.question_id = @question.id

    respond_to do |format|
      if @answer.save
        format.html { redirect_to :back, notice: 'Answer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @answer }
      else
        format.html { redirect_to :back }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to question_path(@answer.question), notice: 'You edited your answer Successfully.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  def upvote
    @answer = Answer.find(params[:id])
    if @answer.owner?(current_user)
      message = "You can't vote for your own answer."
    else
      if current_user.liked? @answer
        message = "You have voted for this answer."
      else
        if current_user.disliked? @answer # will remove downvote, not upvote
          @answer.find_votes(voter_id: current_user.id).first.destroy  # remove downvote.
          @answer.user.add_points(2) # add 2 points previously removed on downvoting
					current_user.add_points(1) # add 1 point previously removed
          increment_votes_count
          message = "Downvote removed!"
        else
          current_user.up_votes @answer
          @answer.user.add_points(10)
          increment_votes_count
          message = "Vote added!" # test time !:)
        end
      end
    end
    redirect_to :back, notice: message
  end

  def downvote
    @answer = Answer.find(params[:id])
    if @answer.owner?(current_user)
      message = "You can't vote your own answer"
    else
      if current_user.disliked? @answer
        message = "You can downvote only once..."
      else
        if current_user.liked? @answer # it will remove the upvote, not downvoting
          @answer.find_votes(voter_id: current_user.id).first.destroy #remove upvote
          @answer.user.substract_points(10)
          decrement_votes_count # adds back +1 vote
          message = "Vote removed"
        else
          current_user.down_votes @answer
          @answer.user.substract_points(2)
					current_user.substract_points(1)
          decrement_votes_count
          message = "You downvoted this answer."
        end
      end
    end
    redirect_to :back, notice: message
	end

  def decrement_votes_count
    @answer.decrement!(:votes_count)
    @answer.save
  end

  def increment_votes_count
    @answer.increment!(:votes_count)
    @answer.save
	end


	# Accept
	def accept_toggle
		@question = Question.find(params[:question_id])
		@answer = Answer.find(params[:id])

    if @question.owner?(current_user)
      if @answer.accepted
        reject_answer
        message = "You rejected the Answer"
      else
        if @question.has_accepted_answer?
    			accepted_answer = @question.answers.where(accepted: true).first
          accepted_answer.update_attributes(accepted: false)
          accept_answer
          message = "Accepted answer was changed!"
    		else
          accept_answer
          message = "You successfully accepted this Answer!"
    		end
      end
    else
      message = "I see what you did there..." # in case someone does a hack
    end

    respond_to do |format|
      format.html { redirect_to :back, notice: message }
      format.js
    end
	end

  def accept_answer
    @answer.update_attributes(accepted: true)
    @answer.user.add_points(15) # Add 15 Points To Answer.User
    @question.user.add_points(2) # Add 2 Points for Accepting
  end

  def reject_answer
    @answer.update_attributes(accepted: false)
    @answer.user.substract_points(15) # Add 15 Points To Answer.User
    @question.user.substract_points(2) # Add 2 Points for Accepting
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:question_id, :body)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<%#=link_to 'Edit', edit_answer_path(answer) %>
<%#= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %>
<div class="row-fluid">

  <div class="span1">
    <div style="text-align: center;">
      <div class="votebar-question">
        <ul>
          <li>
            <%= link_to "", upvote_question_answer_path(@question, answer),
                        class: "fui-triangle-up", title: "This Answer is Useful" %>
          </li>
          <li style="color: #bcbcbc; font-weight: bold">
            <%= answer.votes_count %>
          </li>
          <li>
            <%= link_to "", downvote_question_answer_path(@question, answer),
                        class: "fui-triangle-down", title: "This Answer is not Useful" %>
          </li>
          <% if current_user == @question.user %>
              <% if answer.accepted?  %>
                <li>
                  <%= link_to "", accept_toggle_question_answer_path(@question, answer, answer: "reject"),
                              class: "fui-check accepted_answer", id: "accept_toggle_#{answer.id}", title: "The Question owner accepted this as the best answer", remote: true %>
                </li>
              <% else %>
                <li>
                  <%= link_to "", accept_toggle_question_answer_path(@question, answer, answer: "accept"),
                              class: "fui-check ", id: "accept_toggle_#{answer.id}", remote: true %>
                </li>
              <% end %>
          <% else %>
            <% if current_user == @question.user %>
              <% if answer.accepted?  %>
                <li>
                  <%= link_to "", accept_toggle_question_answer_path(@question, answer),
                              class: "fui-check accepted_answer" %>
                </li>
              <% end %>
            <% else %>
              <% if answer.accepted? %>
                <span class="fui-check accepted_answer" title="The Question owner accepted this as the best answer"></span>
              <% end %>
            <% end %>
          <% end %>
        </ul>
        <div id="message_<%= answer.id %>"></div>
      </div>
    </div>
  </div>

  <div class="span8">
    <div class="answr_inner_body">
      <%= sanitize(raw(answer.body)) %>
    </div>

    <div class="quest_uc">
      <div class="pull-left">

        <% if can? :update, @answer %>
          <small><%= link_to 'Edit', edit_question_answer_path(@question, answer) %></small> |
        <% end %>

        <% if can? :destroy, @answer %>
        <small><%= link_to 'Delete', question_answer_path(@question, answer), :data => { :confirm => "Are you sure you want to delete your Question?" }, method: :delete %></small>
        <% end %>

      </div>

      <!-- Question Owner(User) -->
      <div class="pull-right">
        <td class="post-signature owner">


          <div class="user-info ">
            <div class="user-action-time">
              answered <%= time_ago_in_words(answer.created_at) %> ago
            </div>
            <div class="user-avtr32">
              <%= link_to (image_tag(answer.user.avatar(:mini))), answer.user %>
            </div>
            <div class="user-details">
              <%= link_to answer.user.user_name, answer.user %> 
              <span class="reputation-score" title="reputation score" id="reputation-score-<%= answer.id %>">
                <%= answer.user.points %>
              </span>
            </div>
          </div>

        </td>
      </div>
    </div>

    <br style="clear:both" /> <!-- So dirty! -->
    <div class="clear_it_nicely"></div>


  </div>


</div>


app/views/answers/_form.html.erb
<%= simple_form_for [@question, @answer] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :body, as: :ckeditor, label: false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-info" %>
  </div>
<% end %>

app/views/answers/accept_toggle.js.erb
<% if params[:answer] == "reject" %>
	$('#accept_toggle_<%= @answer.id %>').removeClass('accepted_answer').attr('href', '/questions/another-ajax-test/answers/<%= @answer.id %>/accept_toggle?answer=accept'); // this will add/remove acctepted class to the accepted mark
	$('#message_<%= @answer.id %>').html('Answer rejected!');
<% elsif params[:answer] == "accept" %>
	$('#accept_toggle_<%= @answer.id %>').addClass('accepted_answer').attr('href', '/questions/another-ajax-test/answers/<%= @answer.id %>/accept_toggle?answer=reject'); // this will add/remove acctepted class to the accepted mark
	$('#message_<%= @answer.id %>').html('Answer accepted!');
<% end %>
$('#reputation-score-<%= @answer.id %>').html('<%= @answer.user.points %>');  // this will update user points, user who answered
$('#question_owner_reputation_score_<%= @question.id %>').html('<%= @question.user.points %>'); // this will update user points, user who asked

app/views/answers/edit.html.erb
<h1>Edit your answer</h1>

<%= render 'form' %>

<%= link_to 'Back', @question %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<%= render @answers %>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', question_answers_path %>

app/views/answers/show.html.erb
<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @answer.body %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>