config/routes.rb
Terora::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


	root :to => 'questions#index'

  resources :tags
	resources :updates

  get "tags/show"
  resources :questions do
		resources :answers do
		  member do
			  get :upvote
			  get :downvote
				get :accept_toggle
			end
		end
		member do
			get :upvote
			get :downvote
		end
	end

  get 'get_started/welcome'
	get 'pages/home'
	get 'pages/tags'
	get "about/home"

  devise_for :users, :controllers => { :registrations => 'registrations' },
		:path => '', :path_names => {:sign_in => 'login'}

	# User Profile
	get 'users/show'
	get 'user/:id' => 'users#show', as: :user


	# Help
	get "help" => 'help#home', as: :help
	get 'help/asking' => 'help#asking'
	get 'help/answering' => 'help#answering'
	get 'help/reputation' => 'help#reputation'
	get 'help/account' => 'help#account'

	# About
	get "about" => 'about#home'

	# Error Pages
	get "errors/error_404"
	get "errors/error_500"

	unless Rails.application.config.consider_all_requests_local
		get '*not_found', to: 'errors#error_404'
	end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

	# 1 = Registered
	# 2 = Banned
	# 3 = Moderator
	# 4 = Administrator

  def initialize(user)

		user ||= User.new # guest user (not logged in)

		if user.role_id == 4
			can :manage, :all # user can perform any action on any object
		else
			can :read, :all # user can read any object
			can :upvote, :all
			can :downvote, :all
			can :accept_toggle, Answer
			can :create, Question # can create Question

			# Can Update Question if owner
			can :update, Question do |question|
				question.try(:user) == user || user.role_id == 3
			end

			# Can destroy Question if owner
			can :destroy, Question do |question|
				question.try(:user) == user || user.role_id == 3
			end
		end



    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ActiveRecord::Base

	acts_as_votable

	belongs_to :user
	belongs_to :question

	validates :body, :presence => true
	validates :question_id, :presence => true
	validates :user_id, :presence => true

	def owner?(user)
		if self.user_id == user.id
		  return true
		 else
		 	return false
    end
	end
end

app/models/question.rb
class Question < ActiveRecord::Base
	is_impressionable
	acts_as_votable

	extend FriendlyId
	friendly_id :title, :use => [:slugged, :finders]

	belongs_to :user
	has_many :answers, :dependent => :destroy

  has_many :taggings
  has_many :tags, through: :taggings

	validates :title, :presence => true, length: { minimum: 15 }
	validates :body, :presence => true, length: { minimum: 30 }
	validates :user_id, :presence => true

	def has_accepted_answer?
		self.answers.where(accepted: true).any?
	end

	def owner?(user)
		if self.user_id == user.id
		  return true
		 else
		 	return false
    end
	end

  def self.tagged_with(name)
    Tag.find_by_name!(name).questions
  end

  def tag_list
    tags.map(&:name)
  end

  def tag_with(tags)
  	old_tags = self.tags.pluck(:name).unshift("")
  	unless old_tags == tags # if tags were not updated no action will be done.
	  	self.tags.delete_all
	  		# code here (in the future)
	  	tags.map do |n|
	    	tag = Tag.where(name: n.strip).first
	    	if tag.present?
	    		tagging = Tagging.find_or_create_by_tag_id_and_question_id(tag.id, self.id)
	    	  #Tagging.create(tag_id: tag.id, question_id: self.id)
	    	end
	 	  end
	 	end
  end

  def tag_list=(names)
  	self.tags = names.split(",").map do |n|
    	Tag.where(name: n.strip).first!
 	  end
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :questions, through: :taggings

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :question

end

app/models/update.rb
class Update < ActiveRecord::Base

	extend FriendlyId
	friendly_id :title, :use => [:slugged, :finders]

	validates :title, :presence => true
	validates :body, :presence => true
	# validates :cover, :presence => true

	# Cover
	has_attached_file :cover, styles: { cover: "870x200#" },
										:default_url => 'defulatpath.com',
										:path => ":rails_root/public/system/:attachment/:id/:style/:filename",
										:url => "/system/:attachment/:id/:style/:filename"

	validates_attachment :cover, content_type: { content_type: ['image/jpeg',
																															 'image/jpg',
																															 'image/png'] },
											 size: { less_than: 3.megabytes }


end

app/models/user.rb
class User < ActiveRecord::Base

  has_merit
	acts_as_voter

	extend FriendlyId
	friendly_id :user_name, :use => [:slugged, :finders]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	validates :first_name, :presence => true
	validates :user_name, :presence => true, :uniqueness => true
	validates :email, :presence => true, :uniqueness => true


	# User Avatar
	has_attached_file :avatar, styles: { mini: "32x32#", profile: "180x180#"},
										:default_url => 'https://s3.amazonaws.com/leagueio/design/user-profile/missing-image.png',
										:path => ":rails_root/public/system/:attachment/:id/:style/:filename",
										:url => "/system/:attachment/:id/:style/:filename"

	validates_attachment :avatar, content_type: { content_type: ['image/jpeg',
																															 'image/jpg',
																															 'image/png'] },
											 size: { less_than: 3.megabytes }


	# Relationships
	has_many :questions
	has_many :answers
	belongs_to :role


	before_create :set_default_role


	private

	def set_default_role
		self.role ||= Role.find_by_name('registered')
	end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<!-- UserVoice JavaScript SDK (only needed once on a page) -->
<script>(function(){var uv=document.createElement('script');uv.type='text/javascript';uv.async=true;uv.src='//widget.uservoice.com/IpPxZh3zR4HjDwgS3Xqupg.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(uv,s)})()</script>

<!-- A tab to launch the Classic Widget -->
<script>
  UserVoice = window.UserVoice || [];
  UserVoice.push(['showTab', 'classic_widget', {
    mode: 'feedback',
    primary_color: '#34495e',
    link_color: '#007dbf',
    forum_id: 225819,
    tab_label: 'Feedback',
    tab_color: '#34495e',
    tab_position: 'bottom-left',
    tab_inverted: false
  }]);
</script>

<div class="site-footer">

  <ul class="site-footer-links right">
    <li><%= link_to "Tags", tags_path %></li>
    <li><%= link_to "Help", help_path %></li>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Blog", updates_path %></li>
  </ul>

  <%= link_to root_path do %>
    <span class="mega-octicon octicon-mark-github">
      <i class="fui-bubble"></i>
    </span>
  <% end %>

  <ul class="site-footer-links">
    <li>© <%= Time.now.year %> League I/O</li>
    <li><%= link_to "Facebook", "https://www.facebook.com/leagueio", :target => '_blank' %></li>
    <li><%= link_to "Twitter", "https://twitter.com/Leagueio", :target => '_blank' %></li>
    <li><a href="#">Contact</a></li>
  </ul>
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44908657-1', 'leagueio.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<br>
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target="#nav-collapse-03">
      </button>
      <%= link_to "League I/O", root_path, class: "brand" %>
      <div class="nav-collapse collapse" id="nav-collapse-03" data-no-turbolink>

        <ul class="nav pull-right">
          <li class="divider"></li>

          <% if user_signed_in? %>
            <li><%= link_to 'Tags', tags_path %></li>
            <li><%= link_to 'Ask Question', new_question_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-no-turbolink>
                <%= current_user.first_name %><b class="caret"></b>
              </a>
              <ul class="dropdown-menu" data-no-turbolink>
                <li><%= link_to "My Profile", current_user %></li>
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
            <% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
        </ul> <!-- /nav -->

      </div><!--/.nav-collapse -->
    </div>
  </div>
  <% if user_signed_in? %>
    <div class="scnd_ndr_mn_cnt">
      <ul class="scnd_ndr_mn">
        <li class="active">
          <div style="text-align: right">
            <%= current_user.user_name %>  <%= current_user.points %>
          </div>
        </li>
      </ul>
    </div>
  <% end %>
</div> <!-- /navbar-inverse -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns:fb="http://ogp.me/ns/fb#">
<head>
  <title>League I/O</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= display_meta_tags :site => 'League I/O' %>
  <meta property="fb:app_id" content="557996937600543" />
  <meta property="og:site_name" content="League I/O" />
  <meta property="og:locale" content="en_US" />

  <meta property="og:title" content="League I/O" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="http://www.leagueio.com" />
  <meta property="og:image" content="https://s3.amazonaws.com/leagueio/design/image-meta.png" />
  <meta property="og:description" content="League I/O is for professional and enthusiast League of Legends Players, people who love the Game and want to contribute to the Community."  />
  <meta name="google-site-verification" content="RQ8dTm5vYDQ9KcoCNTMClM8Pya6KBBwsPN5-vHtga1g" />

</head>
<body>

<!-- Facebok SDK -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=105229212914030";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<!-- Facebok SDK END -->

<div class="container">

  <%= render 'layouts/header' %>

  <% flash.each do |name, msg| %>
    <%= content_tag(:div, class: "alert alert-#{name}") do%>
      <%=msg%>
      <button type="button" class="close fui-cross" data-dismiss="alert"></button>
    <%end%>

  <% end %>

  <%= yield %>

  <%= render 'layouts/footer' %>

</div>



</body>
</html>

app/views/layouts/errors.html.erb
<!DOCTYPE html>
<html xmlns:fb="http://ogp.me/ns/fb#">
<head>
  <title>League I/O</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
<%= display_meta_tags :site => 'League I/O' %>
</head>
<body>

  <div class="container">
    <%= render 'layouts/header' %>

    <% flash.each do |name, msg| %>
      <%= content_tag(:div, class: "alert alert-#{name}") do%>
        <%=msg%>
        <button type="button" class="close fui-cross" data-dismiss="alert"></button>
      <%end%>

    <% end %>

    <div class="error_hero_unit">
      <h1>Amumu cries now :( Something broke here  </h1>
    </div>

    <div class="error_hero_unit_beneath">
      <small>
        If you think this is a serious App Problem,
        feel free to report us here
        <%= mail_to "support@leagueio.com", "here", subject: "I want to report a bug",
                    body: "Explain to us what exactly happened and from which link you are coming" %>
      </small>
    </div>

    <%= yield %>

    <!-- UserVoice JavaScript SDK (only needed once on a page) -->
    <script>(function(){var uv=document.createElement('script');uv.type='text/javascript';uv.async=true;uv.src='//widget.uservoice.com/IpPxZh3zR4HjDwgS3Xqupg.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(uv,s)})()</script>

    <!-- A tab to launch the Classic Widget -->
    <script>
      UserVoice = window.UserVoice || [];
      UserVoice.push(['showTab', 'classic_widget', {
        mode: 'feedback',
        primary_color: '#34495e',
        link_color: '#007dbf',
        forum_id: 225819,
        tab_label: 'Feedback',
        tab_color: '#34495e',
        tab_position: 'bottom-left',
        tab_inverted: false
      }]);
    </script>

  </div>

</body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %>
  <div class="row-fluid">

    <div class="span9">
      <%= render @questions %>
    </div>

    <div class="span3">

      <div class="index_wlcm_beta">
        Welcome to the closed Beta <br>
        <%= current_user.first_name %>
        <br>
        <br>
        Feel free to roam around <br>
        and give us Feedback
      </div>

    </div>

  </div>
<% else %>
  <section class="home-hero">
    <div class="hero-content">
      <div class="row">
        <div class="span8 offset2">
          <hgroup>
            <h1><br><br></h1>
            <br>
            <h2>
              League I/O is a question and answer site
              for professional and enthusiast League of Legends
              Players.
            </h2>
          </hgroup>
        </div>
      </div>

      <div class="row">

        <%= link_to "Sign Up", new_user_registration_path,
                    class: "btn btn-huge btn-info" %>

      </div>
    </div>
  </section>
<% end %>

app/views/pages/tags.html.erb
<% tag_cloud Question.tag_counts, %w[s m l] do |tag, css_class| %>
  <%= link_to tag.name, tag_path(tag.name), class: css_class %>
<% end %>